export const DEMO_IMAGES = [
  {
    id: "DEMO-SAR-001",
    label: "DEMO IMAGE — Sentinel-1 SAR (Arabian Sea)",
    region: "Arabian Sea",
    location: { lat: 19.2, lon: 64.5, label: "Arabian Sea · Off Mumbai" },
    url: "/demo/sar/demo-sar-current.png",
    comparisonId: "DEMO-SAR-000",
    expectedConfidence: 0.91,
    expectedAnomaly: true,
    affectedArea: 23,
  },
  {
    id: "DEMO-SAR-PREVIOUS-001",
    label: "DEMO IMAGE — Sentinel-1 SAR Previous (Arabian Sea)",
    region: "Arabian Sea",
    location: { lat: 19.2, lon: 64.5, label: "Arabian Sea · Off Mumbai" },
    url: "/demo/sar/demo-sar-previous.png",
    comparisonId: "DEMO-SAR-000",
    expectedConfidence: 0.0,
    expectedAnomaly: false,
    affectedArea: 0,
  },
  {
    id: "DEMO-OPT-001",
    label: "DEMO IMAGE — Optical (Persian Gulf)",
    region: "Persian Gulf",
    location: { lat: 26.8, lon: 52.3, label: "Persian Gulf" },
    url: "/demo-images/demo-opt-1.jpg",
    comparisonId: "DEMO-OPT-000",
    expectedConfidence: 0.68,
    expectedAnomaly: true,
    affectedArea: 12,
  },
];
